version: '3'

services:
  # Kong Gateway en mode déclaratif
  kong:
    image: kong:latest
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    volumes:
      - ./kong.yml:/kong/kong.yml:ro

  # Interface d'administration Konga
  konga:
    image: pantsel/konga:next
    container_name: konga
    environment:
      NODE_ENV: development
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
    ports:
      - "1337:1337"
    depends_on:
      - kong

  # Base de données pour le service d'authentification
  auth-db:
    image: postgres:13
    container_name: auth-db
    environment:
      POSTGRES_USER: auth
      POSTGRES_DB: auth
      POSTGRES_PASSWORD: authpass
    volumes:
      - auth_data:/var/lib/postgresql/data
      - ./auth-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Service d'authentification
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=6g5X8esCdIIuhcvwkuASQAGGCNyflapWja98//0h8tY=
      - DB_HOST=auth-db
      - DB_USER=auth
      - DB_PASSWORD=authpass
      - DB_NAME=auth
    depends_on:
      auth-db:
        condition: service_healthy

  # Service des produits
  products-service:
    build: ./products-service
    container_name: products-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development

volumes:
  auth_data: 