version: '3.8'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    volumes:
      - kong_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  kong:
    image: kong:latest
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      kong-database:
        condition: service_healthy
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    command: sh -c "kong migrations bootstrap && kong start"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10

  konga:
    image: pantsel/konga:latest
    container_name: konga
    environment:
      NODE_ENV: development
    ports:
      - "1337:1337"
    depends_on:
      - kong

  auth-db:
    image: postgres:13
    container_name: auth-db
    environment:
      POSTGRES_USER: auth
      POSTGRES_DB: auth
      POSTGRES_PASSWORD: authpass
    volumes:
      - auth_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=6g5X8esCdIIuhcvwkuASQAGGCNyflapWja98//0h8tY=
      - DB_HOST=auth-db
      - DB_USER=auth
      - DB_PASSWORD=authpass
      - DB_NAME=auth
    depends_on:
      - auth-db
      - kong

  products-service:
    build: ./products-service
    container_name: products-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - kong

volumes:
  kong_data:
  auth_data: 